### ISSUE TITLE
Fix for #9 not on supermarket

### ISSUE THREAD

**Issue by donaldguy** [schubergphilis/sbp_packer#12]
Can you please do a release? 

or are you still holding out for sit/chef-packer#25 to resolve in your favor?

**Comment by andyrepton** [comment]
Hi there!

I was hopefully waiting for https://github.com/schubergphilis/sbp_packer/pull/11 actually, but if he has not updated it by the time I wake up and get to work I will push a release (approx 9 hours).

Seth
