### ISSUE TITLE
Tags / Supermarket Versions not in Sync

### ISSUE THREAD

**Issue by tknerr** [schubergphilis/sbp_packer#19]
Just noticed that the tags in this repo are totally not in sync:

 * most of the tags for the corresponding supermarket versions are missing
 * 1.4.6 was tagged 3 days ago but not published in supermarket yet

**Comment by sbotman** [comment]
Just checked and I don't have the rights on this one within the supermarket.
@Seth-Karlo can you update the supermarket?

**Comment by svanharmelen** [comment]
Uploaded the latest version to the Supermarket!

**Comment by tknerr** [comment]
@sbotman @svanharmelen do you also have the older tags still around in your local repos and mind to `git push --tags` them?

I was using an older version from supermarket and it was really hard to find / guess the corresponding source code reference otherwise.

Final suggestion / nit-picking while I was looking for changes between 1.4.6 and 1.4.7 => the CHANGELOG is not up-to-date since a few patch versions ;-)

**Comment by sbotman** [comment]
I just cloned this last week, so don't have any local changes. Tnx for the reminder, will update the changelog next time. But the luckily we still have the commit messages ;)
