### ISSUE TITLE
URL should not assume filename naming convention

### ISSUE THREAD

**Issue by haidangwa** [schubergphilis/sbp_packer#2]
In https://github.com/schubergphilis/sbp_packer/blob/master/recipes/install_binary.rb#L13, the `url` parameter assumes that the zip filename is in the form with underscores. This is true when the zip file comes from packer's download. However, we have servers behind a firewall that don't have outbound access to download directly from external websites. Instead, we host the packer zip file on an internal Nexus server. Nexus renames artifacts that get uploaded to it using a dash instead of an underscore. The packer zip file name should be a configurable node attribute to allow for this case.

**Comment by andyrepton** [comment]
Fixed by PR #3
